---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miniflux-database
spec:
  dependsOn:
    - name: plugin-barman-cloud
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: kubernetes/apps/rss/miniflux/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rss
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miniflux
spec:
  dependsOn:
    - name: miniflux-database
  interval: 1h
  path: kubernetes/apps/rss/miniflux/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rss
  wait: false
