---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miniflux-database
spec:
  dependsOn:
    - name: plugin-barman-cloud
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: kubernetes/apps/rss/miniflux/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rss
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miniflux-db
spec:
  dependsOn:
    - name: cluster
      namespace: database
  interval: 1h
  path: kubernetes/components/postgres/base/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
  timeout: 5m
  retryInterval: 2m
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      inProgress: "!has(status.applied)"
      failed: status.applied == false
      current: status.applied == true
  postBuild:
    substitute:
      APP: miniflux
      OWNER: miniflux
      DATABASE_EXTENSIONS: "[{name: hstore}]"

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app miniflux
spec:
  components:
    - ../../../../components/postgres/cert
  dependsOn:
    - name: miniflux-db
    - name: pocket-id-operator
      namespace: security
  interval: 1h
  path: kubernetes/apps/rss/miniflux/app
  prune: true
  postBuild:
    substitute:
      PG_APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rss
  wait: false
