---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-danbooru
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  postgresql:
    parameters:
      timezone: ${CLUSTER_TZ}
  storage:
    size: 10G
    storageClass: democratic-csi-hostpath
  monitoring:
    enablePodMonitor: true

  bootstrap:
    # initdb:
    #   database: danbooru
    #   owner: danbooru
    recovery:
      source: pg-danbooru-restore
      database: danbooru
      owner: danbooru

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-danbooru-store
        serverName: pg-danbooru

  externalClusters:
    - name: pg-danbooru-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: pg-danbooru-store
          serverName: pg-danbooru
