---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  refreshInterval: 15m
  target:
    name: grafana-secret
    template:
      data:
        GF_SECURITY_ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: grafana
