---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vaultwarden
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  postgresql:
    parameters:
      timezone: ${CLUSTER_TZ}
  storage:
    size: 5G
    storageClass: democratic-csi-hostpath
  monitoring:
    enablePodMonitor: true

  bootstrap:
    # initdb:
    #   database: vaultwarden
    #   owner: vaultwarden
    recovery:
      source: pg-vaultwarden-restore
      database: vaultwarden
      owner: vaultwarden

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-vaultwarden-store
        serverName: pg-vaultwarden

  externalClusters:
    - name: pg-vaultwarden-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: pg-vaultwarden-store
          serverName: pg-vaultwarden
