---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &name postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8
  instances: 2

  primaryUpdateMethod: switchover

  certificates:
    serverCASecret: postgres-server-ca
    serverTLSSecret: postgres-server-cert
    clientCASecret: postgres-client-ca
    replicationTLSSecret: postgres-replication-cert

  postgresql:
    parameters:
      max_connections: "100"
      random_page_cost: "1.1"
      # Memory
      shared_buffers: 256MB # 25% of mem limit
      effective_cache_size: 768MB # 75% of mem limit
      # WAL
      max_wal_size: 1GB
      wal_compression: lz4

    pg_hba:
      - hostssl all all all cert clientcert=verify-full map=pooler-map
    pg_ident:
      - pooler-map pooler-rw all

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: 100m
      memory: 512Mi # shared_buffers x 2
    limits:
      memory: 1Gi

  storage:
    size: 20G
    storageClass: ceph-block

  bootstrap:
    # initdb: {}
    recovery:
      source: &src postgres-restore
      recoveryTarget:
        targetTLI: "1"

  managed:
    roles:
      - name: pooler-rw
        ensure: present
        login: true
        superuser: false
        disablePassword: true

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: &store postgres-store

  externalClusters:
    - name: *src
      plugin:
        name: *plugin
        parameters:
          barmanObjectName: *store
          serverName: *name

---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name postgres
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: *name
