---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiomuse-ai-database
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: democratic-csi
      namespace: democratic-csi
  interval: 1h
  path: kubernetes/apps/ai-system/audiomuse-ai/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai-system
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app audiomuse-ai
spec:
  components:
    - ../../../../components/dragonfly
  dependsOn:
    - name: audiomuse-ai-database
    - name: dragonfly
      namespace: database
  interval: 1h
  path: kubernetes/apps/ai-system/audiomuse-ai/app
  prune: true
  postBuild:
    substitute:
      APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai-system
  wait: true
