apiVersion: v1
kind: Secret
metadata:
    name: vault-secret
stringData:
    secretId: ENC[AES256_GCM,data:WOCnSwC9zkjQR793Vl2rYXsEdAk1SuVE17e+oHmcnGIHH8Vv,iv:Pw3sQVDNYQbJFUIsrzuvrxqhOHbN96GvpyCz1i+x+Qo=,tag:STH6ndNedrZ4E5pYbLGw8A==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlI1V1Vra29tZXpoVDZq
            Q3g5Ty9aWGJtM2FmYk9KY0dlQ0tZbHRvN1V3CkxuVTVVWEVzU21LTDRUR29iUXpN
            TG1YVjVXM3hZMzFFM0xicDFJM1dLVlEKLS0tIFE1TzlTSUlDZ1pibkVuK0FzQnAz
            YmoyTU1RY1p4RmE4K1VBSURyblhEbXcKTvvIQW+sGq3PsR9mtw6EtHBmCqmm9R8/
            G7YVLcOiNfsZTj87VE9xtrnzL5iRx1XN6zqoCTEbSgK67jul4HmASA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T07:30:13Z"
    mac: ENC[AES256_GCM,data:hI9Gwy44QYzy3qV6uxGj9QYnSa93HE7hYoyKKmfcZXMhMI2Se6TcBpyx6NVpKuAZBTXtz1CLl55CjGUew7sw8SnCBcvtjaLUpzFNWvt8BDk+fEOwJf888WGVbYZ/PkEmlzNmbfFCoi8QJqR5cIiTU2ojL1dl6mDQTDb6E56/Gpg=,iv:Okp7XNEPYV/AM2uTg1MPTDyHcVNMVvHNtRGdJ1tZ25o=,tag:TszoBRrz0dawx6sRvWwnDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
