---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: alertmanager-secret
    template:
      data:
        BOT_TOKEN: "{{ .BOT_TOKEN }}"
        HEARTBEAT_URL: "{{ .HEARTBEAT_URL }}"
        PUSHOVER_APP_TOKEN: "{{ .PUSHOVER_APP_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: alertmanager
