apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:XETWEy7lnhovzhqhS687Ig0yLaAK+Zm8jZN8yu2R2W+X31bP/U2vSjWBRjORBw==,iv:RFL2dXT6tJWg3+Phb1TWjIKbd0bQyqMxvGUXNMlSm18=,tag:bx6Z4pAFHcxpfbDgladGRQ==,type:str]
    HEARTBEAT_URL: ENC[AES256_GCM,data:/5ijlHqz27aDrZTh27xxMXTV0Bv/W/jIyRZUHw==,iv:0a/3YZH6AQPfVHM/MtBOMrcr8SVHKfa4p/nR2fi3TGw=,tag:6uH7+beUYQs7IYASpSheIw==,type:str]
    PUSHOVER_APP_TOKEN: ENC[AES256_GCM,data:43WPmLKOxoLJw1e5hZN0Odv7CHvcCoLug/3lxLHB,iv:4yXsSWXc2jt3mm99awBZLppBaglEgZufsQttG6Rp/S4=,tag:9OCeN3rx++BxI5+3enTOGQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:ly0uk5vx85V0LCHnxRXZ9svvRTzdMkSqcJgY2G3K,iv:W/TwEVzgjgQ3NqVspybNkvGKHz9UPoQFKBY4OkujWws=,tag:tga2rPCRCPhSiA+dDZLGyg==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MW1yMGphbTdVOVByU2pD
            TFVxc1hCWnN4SElWR2JSNGFWdFVUekNSd0FvCm9kVjZMQUhoVGZhVzVWZldzRVhD
            eDNHbVZuM3BScnYzQVpPblhvUmZDak0KLS0tIHkyOHNmdzNCbnhxeEdmRlgzTm15
            T3kvUHk0TjFkNVVZTE5OQk5tNHZ1TXMKs2wBb1NylGhLb97c1/5mMIyGtEMbp94j
            SKvdm2w7v8PQxbZJHQqKE9tDMN1pCjqHYHbIzFQ6unq79EtJKa9wbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T10:49:49Z"
    mac: ENC[AES256_GCM,data:z/xOyNp5aA2OKWSP1VrobjRMAD7PXmtaZTgD7fWe1z3Vu7cLkkfrxTHVzFp0Tbj8oH1jM3gSTNXd2fqHk54iQfhB3QTqJ7BV9Gldk3TnrOc3nk6P3m27VVtZ1FX0cWkENDAZbn04ZL62LkNyhTwWUsbwHHDgBGmUeDP5RYpLbK0=,iv:i8N5b/bzXIin0GBHjOzD7k/fr0i6DMsYT4aDuSJsqi8=,tag:np47qAEnzWj0qXT8RvMsCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
