---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suwayomi
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      suwayomi:
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.2.2211@sha256:3f65ed696f836cc9db2d3c294eb8239a9cdd93d99831397cc75f84267b09a08e
            env:
              BIND_PORT: &port 4567
              WEB_UI_CHANNEL: "preview"
              AUTO_DOWNLOAD_CHAPTERS: true
              UPDATE_EXCLUDE_UNREAD: "false"
              UPDATE_EXCLUDE_STARTED: "false"
              UPDATE_EXCLUDE_COMPLETED: "false"
              DOWNLOAD_AS_CBZ: "true"
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
      media:
        type: nfs
        server: nas.internal
        path: /mnt/data_pool/data
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk/downloads/manga
            subPath: media/comics/manga
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.mistelinn.org"
        parentRefs:
          - {name: envoy-internal, namespace: network}
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        ports:
          http:
            port: *port
