[env]
KUBECONFIG = "{{config_root | canonicalize}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root | canonicalize}}/.minijinja.toml"
TALOSCONFIG = "{{config_root | canonicalize}}/talosconfig"
LEFTHOOK_OUTPUT = "false"

_.file = [
  "{{config_root}}/.secrets.env",
]

[hooks]
enter = "just doctor"

[tools]
"gum" = "latest"
"just" = "latest"
"uv" = "latest"
"pipx:flux-local" = "latest"
"aqua:cli/cli" = "latest"
"aqua:fluxcd/flux2" = "2.8.8"
"aqua:helm/helm" = "4.2.0"
"aqua:helmfile/helmfile" = "1.5.2"
"aqua:jqlang/jq" = "latest"
"aqua:kubernetes-sigs/kustomize" = "5.8.1"
"aqua:kubernetes/kubectl" = "1.36.0"
"aqua:siderolabs/talos" = "1.13.2"
"github:mitsuhiko/minijinja" = "latest"
