---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: forgejo-secret
    template:
      data:
        # Admin
        username: "{{ .ADMIN_USERNAME }}"
        email: "{{ .ADMIN_EMAIL }}"
        password: "{{ .ADMIN_PASSWORD }}"
        # OIDC
        key: "{{ .OAUTH_CLIENT_ID }}"
        secret: "{{ .OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: forgejo

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: forgejo-app-secret
    template:
      data:
        oauth2: |
          JWT_SECRET={{ .OAUTH2_JWT_SECRET }}
        security: |
          SECRET_KEY: "{{ .SECURITY_SECRET_KEY }}"
          INTERNAL_TOKEN: "{{ .SECURITY_INTERNAL_TOKEN }}"
  dataFrom:
    - extract:
        key: forgejo
