---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: gitea-secret
    template:
      data:
        # App
        username: "{{ .GITEA_ADMIN }}"
        email: "{{ .GITEA_ADMIN_EMAIL }}"
        password: "{{ .GITEA_ADMIN_PASSWORD }}"
        GITEA_SECRET_KEY: "{{ .GITEA_SECRET_KEY }}"
        GITEA_INTERNAL_TOKEN: "{{ .GITEA_INTERNAL_TOKEN }}"
        # S3
        GITEA_AWS_ACCESS_KEY_ID: "{{ .GITEA_AWS_ACCESS_KEY_ID }}"
        GITEA_AWS_SECRET_ACCESS_KEY: "{{ .GITEA_AWS_SECRET_ACCESS_KEY }}"
        # OIDC
        key: "{{ .GITEA_CLIENT_ID }}"
        secret: "{{ .GITEA_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: gitea
