---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: vaultwarden-secret
    template:
      data:
        ADMIN_TOKEN: "{{ .ADMIN_TOKEN }}"
        SSO_ENABLED: "true"
        SSO_AUTHORITY: "https://authentik.${CLUSTER_DOMAIN}/application/o/bitwarden/"
        SSO_CLIENT_ID: "{{ .SSO_CLIENT_ID }}"
        SSO_CLIENT_SECRET: "{{ .SSO_CLIENT_SECRET }}"
        SSO_SCOPES: openid profile email offline_access

  dataFrom:
    - extract:
        key: vaultwarden
