---
public_baseurl: "https://matrix.mistelinn.org"
presence:
  enabled: true
enable_metrics: true
report_stats: false
suppress_key_server_warning: true
trusted_key_servers:
  - server_name: "matrix.org"
admin_contact: "mailto:admin@mistelinn.org"
enable_search: true
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '169.254.0.0/16'
  - '::1/128'
  - 'fe80::/64'
  - 'fc00::/7'
rc_message:
  per_second: 5
  burst_count: 20
experimental_features:
  # MSC4354: sticky events for matrixRTC user state
  msc4354_enabled: true
database:
  allow_unsafe_locale: true
  args:
    sslcert: /var/run/secrets/postgresql/tls.crt
    sslkey: /var/run/secrets/postgresql/tls.key
    sslrootcert: /var/run/secrets/postgres-server-ca/ca.crt
email:
  smtp_host: smtp-relay.network.svc.cluster.local
  smtp_port: 25
  enable_tls: false
  notif_from: "Matrix <noreply@mistelinn.org>"
