---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/docker-compose.json
services:
  traefik:
    image: traefik:v3.6.12@sha256:171c9c3565b29f6c133f1c1b43c5d4e5853415198e9e1078c001f8702ff66aec
    container_name: traefik
    restart: always
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${ACME_EMAIL}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      ROOT_DOMAIN: ${ROOT_DOMAIN}
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/extra:/config
      - ${APPS_DATASET:-/mnt/data_pool/app}/traefik/acme:/etc/traefik/acme
    networks:
      - default
      - proxy_network
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # security
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    read_only: true

configs:
  traefik-config:
    file: ./config/traefik.yaml

networks:
  proxy_network:
    external: true
