---
# yaml-language-server: $schema=https://schemas.ajgon.casa/other/docker-compose.json
services:
  vault:
    image: hashicorp/vault:2.0.2@sha256:3fd53308acccd9e4e83fde3e6c6cf5b15e0f7fac1ff7510780b8b23f5e4c3de7
    container_name: vault
    restart: unless-stopped
    command: server
    configs:
      - source: vault-config
        target: /vault/config/config.hcl
    volumes:
      - ${APPS_DATASET:-/mnt/data_pool/app}/vault/data:/vault/data
    networks:
      - proxy_network
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      # https://github.com/hashicorp/vault/issues/31919
      SKIP_SETCAP: "true"
      SKIP_CHOWN: "true"
    # ports:
    #   - 8200:8200
    # security
    cap_add:
      - IPC_LOCK
    # traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy_network
      # Vault
      traefik.http.services.vault.loadbalancer.server.port: "8200"
      traefik.http.routers.vault.entrypoints: websecure
      traefik.http.routers.vault.rule: Host(`vault.${ROOT_DOMAIN}`)
      traefik.http.routers.vault.service: vault
      traefik.http.routers.vault.tls: true
      traefik.http.routers.vault.tls.certresolver: letsencrypt

configs:
  vault-config:
    file: ./config/config.hcl

networks:
  proxy_network:
    external: true
