---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: komf-secret
    template:
      data:
        KOMF_KAVITA_API_KEY: "{{ .KOMF_KAVITA_API_KEY }}"
  dataFrom:
    - extract:
        key: komf
