---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.36.3
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: '!has(status.phase) || status.phase != "Running"'
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: '!has(status.phase) || !(status.phase in ["Resolving", "Restoring"])'
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: status.conditions.exists(c, c.type == "Ready" && c.status == "True")
