---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    version: v1.35.4 # renovate: docker=ghcr.io/siderolabs/kubelet
  maintenance:
    windows:
      - start: "0 4 * * 0"
        duration: "4h"
        timezone: "${CLUSTER_TZ}"
  healthChecks:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      expr: status.conditions.filter(c, c.type == "Synchronizing").all(c, c.status == "False")
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")
