---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: forgejo-runner-secret
    template:
      data:
        token: "{{ .RUNNER_K8S_TOKEN }}"
        uuid: "{{ .RUNNER_K8S_UUID }}"
  dataFrom:
    - extract:
        key: forgejo-runner
