---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:66d4ea40fc744ecd0e5b83535b5434ea6351e8d5b1fdab13b04f3bcfa8c32fca
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
restartPolicy: Never
