---
containers:
  - env:
      - name: DEBIAN_FRONTEND
        value: noninteractive
    image: ghcr.io/bjw-s-labs/forgejo-runner:ubuntu-24.04@sha256:73abe5c3630cb94ff2dac75501b94bbb431c893b8528b748be8875e61eae04ac
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
restartPolicy: Never
