---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-database
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: democratic-csi
      namespace: democratic-csi
  interval: 1h
  path: kubernetes/apps/comms/matrix/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: comms
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app matrix
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: matrix-database
  interval: 1h
  path: kubernetes/apps/comms/matrix/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: comms
