---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: services
spec:
  module: https
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        # docker on nas
        - https://traefik.mistelinn.org
        - https://nas.mistelinn.org
        - https://garage.mistelinn.org
        - https://s3.mistelinn.org
        - https://vault.mistelinn.org
