apiVersion: v1
kind: Secret
metadata:
    name: github-token-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:7WZTEtqio9Aeo0enPe/DoKYG/3LUOGGosr/hl/LIMcEb/xyWFvkqCjhwHuOFss0vFKEr4iCjdNNKKYuRmmNzaWUjzHNjq5dbV1BYZBOQZhO3f/cV6fP9KD5uVDb0,iv:j1kTgXKtVsSsdE7vp8GUt96q6HnQyvXqKMrjTIK17Ho=,tag:c8sBd2DpKunWaJsDGhbluA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbUwyNlJRQ01uR0VzQkwv
            WjVmRDUrbCtUcTRWTnZ6eUhJNmgva3hNcGdJCnNOYzNaL1dBdUVwR2FYSmlmOVgv
            WlFJMHVmVmhJR2xzQXRud2RYVmpiekkKLS0tIENTTjg5QjlOakFaMjNtTkplUXdL
            bUlGVjVrdlcwQm92L1loN3IvNjdFL0kKoBU4T5LEeuR6LxRL9xoZ34eR23JYHjBX
            8dKbd/eIROtjJVIzQRuxWcfNAR3misuChgu6+Mdx9pxIjfvtO9VVag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:56:37Z"
    mac: ENC[AES256_GCM,data:/dNULoWWl03r6NSA3tBzcII+vRv2A6p7wkb/VlZuvJ98ooVYpQcxNfOq5+DDQ9hSviJSwmdouLK+WN+p85tC2aNEN9A/q/Bke0i75JqVNdw1k+jrYuJ502YjLdR2AbnHj2j94XDMHHSOIG5rzApIQnkibXod9Ka/t6Z9o2Fzf/Q=,iv:JSpTJ/4bkGDr8zjHx2IUg7N1/zEXciOieZKTT3q7I+o=,tag:7xtWLfwss2KcIZqWXiat1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
