---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: miniflux
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      miniflux:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/miniflux/miniflux
              tag: 2.3.1-distroless@sha256:6361b075e6189c10f3ac7d18733e467bd3bbf965de2ad5a64a0fb9809456989e
            env:
              FETCHER_ALLOW_PRIVATE_NETWORKS: "1"
              BASE_URL: "https://{{ .Release.Name }}.mistelinn.org"
              LOG_DATE_TIME: "1"
              POLLING_SCHEDULER: entry_frequency
              POLLING_FREQUENCY: "15"
              PORT: &port 80
              OAUTH2_PROVIDER: oidc
              OAUTH2_OIDC_PROVIDER_NAME: Authentik
              OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://authentik.mistelinn.org/application/o/miniflux/"
              OAUTH2_REDIRECT_URL: "https://miniflux.mistelinn.org/oauth2/oidc/callback"
              OAUTH2_USER_CREATION: "1"
              RUN_MIGRATIONS: "1"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: pg-miniflux-app
                    key: uri
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        seccompProfile: {type: RuntimeDefault}
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            url: "https://miniflux.mistelinn.org/healthcheck"
        hostnames:
          - "{{ .Release.Name }}.mistelinn.org"
        parentRefs:
          - {name: envoy-external, namespace: network}
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    service:
      app:
        ports:
          http:
            port: *port
