---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: github-mcp-secret
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .OPENCLAW_TOKEN }}"
  dataFrom:
    - extract:
        key: github
