---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: headlamp-secret
    template:
      data:
        OIDC_ISSUER_URL: "https://authentik.${CLUSTER_DOMAIN}/application/o/kubectl/"
        OIDC_CLIENT_ID: kubectl
        OIDC_CLIENT_SECRET: "{{ .KUBECTL_OIDC_CLIENT_SECRET }}"
        OIDC_SCOPES: openid,profile,email
  dataFrom:
    - extract:
        key: kubernetes
