---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
spec:
  dependsOn:
    - name: pocket-id-operator
      namespace: security
  interval: 1h
  path: kubernetes/apps/forgejo-system/renovate-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo-system
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator-jobs
spec:
  components:
    - ../../../../components/dragonfly
  dependsOn:
    - name: dragonfly
      namespace: database
    - name: renovate-operator
  interval: 1h
  path: kubernetes/apps/forgejo-system/renovate-operator/jobs
  prune: true
  postBuild:
    substitute:
      APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo-system
  wait: false
