---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
  oidc:
    provider:
      issuer: "https://id.mistelinn.org"
    clientIDRef:
      group: ""
      kind: Secret
      name: ${APP}-oidc-credentials
    clientSecret:
      group: ""
      kind: Secret
      name: ${APP}-oidc-credentials
    redirectURL: "https://${APP}.mistelinn.org/oauth2/callback"
    logoutPath: "/logout"
