---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rsshub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: rsshub-secret
    template:
      data:
        PIXIV_REFRESHTOKEN: "{{ .PIXIV_REFRESHTOKEN }}"
        FANTIA_COOKIE: "{{ .FANTIA_COOKIE }}"
        EH_IPB_MEMBER_ID: "{{ .EH_IPB_MEMBER_ID }}"
        EH_IPB_PASS_HASH: "{{ .EH_IPB_PASS_HASH }}"
        EH_SK: "{{ .EH_SK }}"
        EH_IGNEOUS: "{{ .EH_IGNEOUS }}"
        HOTLINK_TEMPLATE: "{{ .HOTLINK_TEMPLATE }}"
  dataFrom:
    - extract:
        key: rsshub
