---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: bazarr-secret
    template:
      data:
        BAZARR__AUTH__APIKEY: "{{ .BAZARR_AUTH_APIKEY }}"
  dataFrom:
    - extract:
        key: bazarr
