apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
stringData:
    BAZARR__AUTH__APIKEY: ENC[AES256_GCM,data:bYi2Zi3jFzDQSX885KfLUeAn3GugsPvkd6qgthgldtNeduo9Is4L82UXtQ==,iv:CXigoSyt4keaYHnKMWSIhBdRSs8+Gz1RGBrC0ieaGxA=,tag:RW3nErXMJQ1X/wvEyYn2ug==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdTYrRTlzS21aN05OWURl
            Mk5yM0IrcmwvNmNxeUNJSVNWdzFpWjFpeFVzCndUNFNjcGN1anNnRk81OTlHcUtB
            cDVzY3Q2RlZUa1BwZ1dJd0k5eUkwSWsKLS0tIFhYQ2I3Qkw3VU1LcW4zYnIzQi9o
            WDcxQ0tnZkN4RlQ3dGZKdkVmR21WcTgKwYUHlVgxxCaUsb8x8A/DjFtETZ+fbDlK
            6i4TrgmundxaybH408/VciG/6CABLkdz4qhReR67GPhnadk4U9ienw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T11:16:29Z"
    mac: ENC[AES256_GCM,data:QQ8dRMg5/DitHn0uSMaL93SsvL2OO9S2ZogQ2pCBB31dyyS/ZFMWti7nrSMYpoCoe/jgHvbfrm64c63ZeV7qC2dFjdEmchDEvZLjSOQli5RaJlHkdZssekKVjFE+cSaqDoMBzvXWWltFGTR2m/sb3l8+x9BabYnDpKLu396a1gA=,iv:F+VKX3IUcUPCBtndrg7GOvkpvLkyD6ajnM4ngbR2aPo=,tag:QpacyFkV3Tl5WVTnJSyf6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
