---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: matrix-secret
    template:
      data:
        synapse.yaml: |
          public_baseurl: "https://matrix.${CLUSTER_DOMAIN}"
          presence:
            enabled: true
          enable_metrics: true
          report_stats: false
          suppress_key_server_warning: true
          trusted_key_servers:
            - server_name: "matrix.org"
          admin_contact: "mailto:admin@${CLUSTER_DOMAIN}"
          enable_search: true
          url_preview_enabled: true
          url_preview_ip_range_blacklist:
            - '127.0.0.0/8'
            - '10.0.0.0/8'
            - '172.16.0.0/12'
            - '192.168.0.0/16'
            - '100.64.0.0/10'
            - '169.254.0.0/16'
            - '::1/128'
            - 'fe80::/64'
            - 'fc00::/7'
          rc_message:
            per_second: 5
            burst_count: 20
          experimental_features:
            # MSC3575: original sliding sync API plumbing.
            msc3575_enabled: true
            # MSC4186: native simplified sliding sync implementation in Synapse.
            msc4186_enabled: true
            # MSC4354: sticky events for matrixRTC user state
            msc4354_enabled: true
          database:
            allow_unsafe_locale: true
          email:
            smtp_host: smtp-relay.network.svc.cluster.local
            smtp_port: 25
            enable_tls: false
            notif_from: "Matrix <noreply@${CLUSTER_DOMAIN}>"

        mas.yaml: |
          branding:
            service_name: "${CLUSTER_BRAND} Matrix"
          passwords:
            enabled: false
          account:
            email_change_allowed: true
            displayname_change_allowed: true
          email:
            from: "Matrix Auth <noreply@${CLUSTER_DOMAIN}>"
            reply_to: "No reply <noreply@${CLUSTER_DOMAIN}>"
            transport: smtp
            mode: plain
            hostname: smtp-relay.network.svc.cluster.local
            port: 25
          upstream_oauth2:
            providers:
              - id: 01KH4CXFQFYXJGJ231M2FSVBGK
                human_name: Authentik
                issuer: https://authentik.${CLUSTER_DOMAIN}/application/o/matrix/
                client_id: "{{ .MATRIX_CLIENT_ID }}"
                client_secret: "{{ .MATRIX_CLIENT_SECRET }}"
                userinfo_endpoint: https://authentik.${CLUSTER_DOMAIN}/application/o/userinfo/
                authorization_endpoint: https://authentik.${CLUSTER_DOMAIN}/application/o/authorize/
                token_endpoint: https://authentik.${CLUSTER_DOMAIN}/application/o/token/
                jwks_uri: https://authentik.${CLUSTER_DOMAIN}/application/o/matrix/jwks/
                token_endpoint_auth_method: client_secret_post
                scope: "openid email profile"
                discovery_mode: oidc
                pkce_method: auto
                claims_imports:
                  localpart:
                    action: require
                    template: "{{ `{{ user.preferred_username }}` }}"
                    on_conflict: replace
                  displayname:
                    action: suggest
                    template: "{{ `{{ user.name }}` }}"
                  email:
                    action: suggest
                    template: "{{ `{{ user.email }}` }}"
  dataFrom:
    - extract:
        key: matrix
