---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - httproutes.yaml
  - ocirepository.yaml
  - pocketidoidcclient.yaml
  - pushsecret.yaml
configMapGenerator:
  - name: matrix-configmap
    files:
      - ./resources/synapse.yaml
      - ./resources/mas.yaml
generatorOptions:
  disableNameSuffixHash: true
