---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: matrix-oidc
spec:
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      # Created by the Pocket ID operator from the PocketIDOIDCClient.
      name: matrix-oidc-credentials
  data:
    - match:
        secretKey: client_id
        remoteRef:
          remoteKey: matrix
          property: MATRIX_CLIENT_ID
    - match:
        secretKey: client_secret
        remoteRef:
          remoteKey: matrix
          property: MATRIX_CLIENT_SECRET
