---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea-database
  namespace: flux-system
spec:
  interval: 1h
  path: kubernetes/apps/personal/gitea/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: personal
  wait: true
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: pg-gitea
      namespace: personal
  dependsOn:
    - name: cloudnative-pg
    - name: democratic-csi

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
  namespace: flux-system
spec:
  components:
    - ../../../../components/dragonfly
    - ../../../../components/volsync
  interval: 1h
  path: kubernetes/apps/personal/gitea/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: personal
  dependsOn:
    - name: gitea-database
    - name: democratic-csi
