---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: danbooru
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: danbooru-secret
    template:
      data:
        DANBOORU_SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        DANBOORU_TWITTER_AUTH_TOKEN: "{{ .TWITTER_AUTH_TOKEN }}"
        DANBOORU_TWITTER_CSRF_TOKEN: "{{ .TWITTER_CSRF_TOKEN }}"
        DANBOORU_PIXIV_PHPSESSID: "{{ .PIXIV_PHPSESSID }}"
        DANBOORU_FANTIA_SESSION_ID: "{{ .FANTIA_SESSION_ID }}"
  dataFrom:
    - extract:
        key: danbooru
