---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-matrix
spec:
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  postgresql:
    parameters:
      timezone: ${CLUSTER_TZ}
  storage:
    size: 10G
    storageClass: democratic-csi-hostpath
  monitoring:
    enablePodMonitor: true

  bootstrap:
    # initdb:
    #   database: synapse
    #   owner: matrix
    recovery:
      source: source
      database: synapse
      owner: matrix

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-matrix-store
        serverName: pg-matrix

  externalClusters:
    - name: pg-matrix-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: pg-matrix-store
          serverName: pg-matrix
