apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
stringData:
    CLUSTER_BRAND: ENC[AES256_GCM,data:hsSpsjIGt9Q5,iv:riBL+mbT4HQdJJvnVRqsa6f7HYImCy62ETmfKzYn+wU=,tag:QPaTC1U+/JpXB3EB6nlw2g==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:lRVIOB4Filf9w4GpSg==,iv:RwTfki9DaWB+KOsBHzftMCwh+tFN+6Ho8ArrwcnvBEg=,tag:mi+Bdv1h+nARj+UeqGjbEw==,type:str]
    CLUSTER_TZ: ENC[AES256_GCM,data:rnx6hmvyAmyhIKfWzg==,iv:CCOtstSF5fDApJFJu1sy5diYwhg2EXnIL87sKeNsMUM=,tag:bcYE5q1NbpJVG9g6/aj5CQ==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUHFITlJ4cUp4cVR1dFky
            K2pNTXMzU05MUzFCYy9qb3VlZ0plUTFKMDFNCmhOKzVHUlQzUzhRTHU0cEY3SHZU
            M1JPWG5rU09pN2pOUk4ybEJVYkJsOEUKLS0tIHJlMlhnVGZwTlJzclR0SFFkcEwy
            MldmRUFRTThLeUczLzd6NXczWThQTzgKwPZSh129lzcgYCyZABXXklmbGiA0YFRQ
            3rq0UnlvYeNkt2EZSKr00zyVmdJvyOKYmdyzX1TbbMJsuqMbhZ+QXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T07:34:42Z"
    mac: ENC[AES256_GCM,data:IcYztwCJGGahXYtUMcdNIqakmgmgsOESnjhCXp58HU4QkthuaXPZDf7wRz9CKJSV5OYaOnnbN5rucZ6/5aio8lHBTxssXG9ep3+mX5Yj4EjdRxL0qiJ0abBliNBu65mx/lJjKswq49f8njGRl5uZ0MZ66tcB4ukTy34xsp+FcLU=,iv:OegWo5gR9ZwVGFyR5CC3/tXcZkp/QfP67tsk/QmeGU0=,tag:3Jl1z0EK+xF3Z9cEytfE5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
