---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-audiomuse-ai
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  managed:
    services:
      disabledDefaultServices:
        - "ro"
        - "r"
  storage:
    size: 20G
    storageClass: democratic-csi-hostpath
  monitoring:
    enablePodMonitor: true

  bootstrap:
    # initdb:
    #   database: audiomusedb
    #   owner: audiomuse
    recovery:
      source: pg-audiomuse-ai-restore
      database: audiomusedb
      owner: audiomuse

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-audiomuse-ai-store
        serverName: pg-audiomuse-ai

  externalClusters:
    - name: pg-audiomuse-ai-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: pg-audiomuse-ai-store
          serverName: pg-audiomuse-ai
