---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: danbooru-db
spec:
  dependsOn:
    - name: cluster
      namespace: database
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      inProgress: "!has(status.applied)"
      failed: status.applied == false
      current: status.applied == true
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  path: kubernetes/components/postgres/base/database
  prune: true
  postBuild:
    substitute:
      APP: danbooru
      OWNER: danbooru
      DATABASE_EXTENSIONS: "[{name: btree_gin}, {name: fuzzystrmatch}, {name: pg_trgm}, {name: pgcrypto}, {name: pgstattuple}]"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app danbooru
spec:
  components:
    - ../../../../components/dragonfly
    - ../../../../components/keda
    - ../../../../components/postgres/app-template
  dependsOn:
    - name: danbooru-db
    - name: dragonfly
      namespace: database
  interval: 1h
  path: kubernetes/apps/image/danbooru/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      PG_APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: image
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autotagger
spec:
  components:
    - ../../../../components/gpu
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
  interval: 1h
  path: kubernetes/apps/image/danbooru/autotagger
  prune: true
  postBuild:
    substitute:
      APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: image
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app iqdb
spec:
  components:
    - ../../../../components/kopiur
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: kubernetes/apps/image/danbooru/iqdb
  prune: true
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 10Gi
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: image
