[[stack]]
name = "matchbox"
[stack.config]
server = "nas"
repo = "yukariin/cluster"
webhook_enabled = false
run_directory = "docker/stacks/matchbox"
environment = """
ROOT_DOMAIN="[[ROOT_DOMAIN]]"
"""