---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: slskd-secret
    template:
      data:
        slskd.yml: |
          soulseek:
            username: "{{ .SLSKD_USERNAME }}"
            password: "{{ .SLSKD_PASSWORD }}"
          web:
            authentication:
              disabled: false
              username: "{{ .SLSKD_USERNAME }}"
              password: "{{ .SLSKD_PASSWORD }}"
              jwt:
                key: "{{ .SLSKD_JWT_KEY }}"
                ttl: 604800000
              api_keys:
                soularr:
                  key: "{{ .SOULARR_API_KEY }}"
                  role: ReadWrite
                  cidr: 0.0.0.0/0,::/0
          shares:
            directories:
              - /media/soulseek
              - /media/media/music
            filters:
              - \.ini$
              - Thumbs.db$
              - \.DS_Store$
          retention:
            transfers:
              upload:
                succeeded: 1440 # 1 day
                errored: 30
                cancelled: 5
                failed: 180
              download:
                succeeded: 1440 # 1 day
                errored: 20160 # 2 weeks
                cancelled: 5
                failed: 180
  dataFrom:
    - extract:
        key: slskd
