---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: "${APP}-dragonfly"
spec:
  image: ghcr.io/dragonflydb/dragonfly:v2.0.0@sha256:7426fdb31ddcf7bd9499b4205f36ebaa83b26149ba1609a0d5f8f474b3631233
  args:
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys
    - --lock_on_hashtags
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  networkPolicyEnabled: false
  replicas: ${DRAGONFLY_REPLICAS:=1}
  resources:
    requests:
      cpu: 50m
    limits:
      memory: 512Mi
  podSecurityContext:
    runAsNonRoot: true
    # builtin dfly user
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities: {drop: ["ALL"]}
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app: "${APP}-dragonfly"
