---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-miniflux
spec:
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  postgresql:
    parameters:
      timezone: ${CLUSTER_TZ}
  storage:
    size: 1G
    storageClass: democratic-csi-hostpath
  monitoring:
    enablePodMonitor: true

  bootstrap:
    # initdb:
    #   database: miniflux
    #   owner: miniflux
    recovery:
      source: pg-miniflux-restore
      database: miniflux
      owner: miniflux

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-miniflux-store
        serverName: pg-miniflux

  externalClusters:
    - name: pg-miniflux-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: pg-miniflux-store
          serverName: pg-miniflux
