---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: searxng-mcp
spec:
  alias: searxng_mcp
  params:
    allow_all_keys: true
  workload:
    # renovate: datasource=docker depName=docker.io/isokoliuk/mcp-searxng
    image: docker.io/isokoliuk/mcp-searxng:2.5.1@sha256:47c2c520c06b396b89d34bda8a4cd5961e04e4d35c59b931f63d617be45245b5
    port: 8080
    env:
      - name: SEARXNG_URL
        value: http://searxng.ai-system.svc.cluster.local:8080
      - name: MCP_HTTP_PORT
        value: "8080"
      - name: MCP_HTTP_HOST
        value: 0.0.0.0
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 256Mi
