---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: "1"
        memory: 256Mi

    serviceMonitor:
      create: true

    web:
      config:
        baseURL: "https://flux.mistelinn.org"
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            issuerURL: "https://id.mistelinn.org"
      httpRoute:
        enabled: true
        hostnames:
          - "flux.mistelinn.org"
        parentRefs:
          - name: envoy-internal
            namespace: network
      networkPolicy:
        create: false

  valuesFrom:
    - kind: Secret
      name: flux-web-oidc-credentials
      valuesKey: client-id
      targetPath: web.config.authentication.oauth2.clientID
    - kind: Secret
      name: flux-web-oidc-credentials
      valuesKey: client-secret
      targetPath: web.config.authentication.oauth2.clientSecret
