---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  compression:
    compressor: zstd
  credentialProjection:
    enabled: true
  mover:
    securityContext:
      runAsUser: ${KOPIUR_PUID:=568}
      runAsGroup: ${KOPIUR_PGID:=568}
  repository:
    kind: ClusterRepository
    name: kopia-nas
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  sources:
    - pvc:
        name: ${APP}
  verification:
    deep:
      schedule:
        cron: H 5 1 * * # First of the month at 5am
    quick:
      schedule:
        cron: H 4 * * * # Every day at 4am
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-block}
