---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-openwrt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: external-dns-openwrt-secret
    template:
      data:
        PROVIDER_OPENWRT_LUCIRPC_AUTH_USERNAME: "{{ .LUCIRPC_AUTH_USERNAME }}"
        PROVIDER_OPENWRT_LUCIRPC_AUTH_PASSWORD: "{{ .LUCIRPC_AUTH_PASSWORD }}"
  dataFrom:
    - extract:
        key: openwrt
