apiVersion: v1
kind: Secret
metadata:
    name: external-dns-openwrt
stringData:
    PROVIDER_OPENWRT_LUCIRPC_AUTH_USERNAME: ENC[AES256_GCM,data:JfxThg==,iv:P/Mxrn04KaDeFpAEfkzFNsHUBDYYy4E4pJydLo9/a3k=,tag:B6ZerxO5L/XsE4Y7fbSZWQ==,type:str]
    PROVIDER_OPENWRT_LUCIRPC_AUTH_PASSWORD: ENC[AES256_GCM,data:Z3qr2SFICHY=,iv:a3TWz0cvsJPReJNLZb/ett7bpa1lVjZ+kMAhM5wO/dk=,tag:gMaxG/AaEvqY6WB9xd+dIA==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUFJzUm4xQWtsL3dQcjM5
            Qk4yU2Z6TjArcytRWHUyalBpTHZiTWNpbVVBCkM5OGdlVW94NGJRUEV0alNrMzFH
            Wm9VTi9yNVp2M3ExZHZjd08xaExBVlkKLS0tIEhaOXk4NTY1ODlNSmdQOHp4SUpT
            eU9KTWZ5ZkFuNjR6RTJiVFV6TGVNL00KmAc0FaBGSUgZz0lqmumoBDEWhzQsydEw
            d7axAWAfi9fe83rOYKwvOzxYO6Qhgjrjq2CAl1Alx2lgtdUvBghCww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T08:37:31Z"
    mac: ENC[AES256_GCM,data:5fLCFHJA0IMUbSaYATCKPesb5YW2/pbj6Kta4BUmmxxUwFmlajRjRaCilLP3AYZHHXeLZagDxEW2O59+E98RQsmq/9ObBZ/PmaIYs1BEpmuTDHP/eqlKl7R9mgDnU2kdFwRheLrsxkVFEdI8lcqWpy7P51qDvGLa0whlZN2O+2E=,iv:VLzUan4rA783AV28R+Px5QW6QQWSmax/Ks/FSOj0lio=,tag:8ngY8w3zG8ENWnS7QV3Whw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
