---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: startech
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: startech-secret
    template:
      data:
        RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
        WHITELIST: "{{ .WHITELIST }}"
        OPS: "{{ .OPS }}"
        CF_API_KEY: "{{ .CF_API_KEY }}"
  dataFrom:
    - extract:
        key: minecraft
    - extract:
        key: rcon
