---
# yaml-language-server: $schema=https://schemas.ajgon.casa/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:=1Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: ${VOLSYNC_PUID:=568}
      runAsGroup: ${VOLSYNC_PGID:=568}
      fsGroup: ${VOLSYNC_PGID:=568}
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile: { type: RuntimeDefault }
    repository: "${APP}-volsync-secret"
    sourceIdentity:
      sourceName: "${APP}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=democratic-csi-hostpath}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-democratic-csi-hostpath}"
