---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-authentik
spec:
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  postgresql:
    parameters:
      timezone: ${CLUSTER_TZ}
  storage:
    size: 5G
    storageClass: democratic-csi-hostpath
  monitoring:
    enablePodMonitor: true

  bootstrap:
    # initdb:
    #   database: authentik
    #   owner: authentik
    recovery:
      source: pg-authentik-restore
      database: authentik
      owner: authentik

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: pg-authentik-store
        serverName: pg-authentik

  externalClusters:
    - name: pg-authentik-restore
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: pg-authentik-store
          serverName: pg-authentik
