---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: lidarr-secret
    template:
      data:
        LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY }}"
  dataFrom:
    - extract:
        key: lidarr
