---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitmagnet
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: bitmagnet-secret
    template:
      data:
        TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
  dataFrom:
    - extract:
        key: bitmagnet
