apiVersion: v1
kind: Secret
metadata:
    name: marinara-engine-secret
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:IZbB+U57ZTb8igJ9ExrMQvh5FNG4l/KFoMCDrSVYrUZcEWaJSAdVlVnKmnP3YH0NcSOApHh/idTiuRbfPRxScA==,iv:aAzAcvpHqJsIZyo/sYbrSXBTUY/+TT9PRN3im51UO/0=,tag:SKXYESJxMaYZXQJDfptkEg==,type:str]
sops:
    age:
        - recipient: age19a0awfzsf08spama7j9trxmmdxqqmfhmtxrcxgsyq35y4jj82ausn2a28q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdTYrRTlzS21aN05OWURl
            Mk5yM0IrcmwvNmNxeUNJSVNWdzFpWjFpeFVzCndUNFNjcGN1anNnRk81OTlHcUtB
            cDVzY3Q2RlZUa1BwZ1dJd0k5eUkwSWsKLS0tIFhYQ2I3Qkw3VU1LcW4zYnIzQi9o
            WDcxQ0tnZkN4RlQ3dGZKdkVmR21WcTgKwYUHlVgxxCaUsb8x8A/DjFtETZ+fbDlK
            6i4TrgmundxaybH408/VciG/6CABLkdz4qhReR67GPhnadk4U9ienw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T19:45:42Z"
    mac: ENC[AES256_GCM,data:T4Q2rJOdjnuEZZ1mwOF0H5CC56ilYuolE7oNUjUQUanoC73AqlRIAJaCWfxMt85wN1hqxtrTlRyaOOq3iypi3OtDCkFQc8IMXVIeaehLCZo7ANSXUfkarMppRaatiipS6zMIpOXrsgjLxU5VDm0ZA7wr7RgTynlPnYl/un/F0Vg=,iv:DZpl5eyYXqSl9maRSWME17176qn5GpuwImc8wRWEhHg=,tag:rTk71M3wa3qlN5gpRZdVXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
