---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .SECRET_KEY }}"
        PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
        PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
        PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "true"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
              "SCOPE": [
                "openid",
                "profile",
                "email"
              ],
              "OAUTH_PKCE_ENABLED": true,
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "authentik",
                  "client_id": "{{ .CLIENT_ID }}",
                  "secret": "{{ .CLIENT_SECRET }}",
                  "settings": {
                    "server_url": "https://authentik.${CLUSTER_DOMAIN}/application/o/paperless/.well-known/openid-configuration",
                    "claims": {"username": "email"}
                  }
                }
              ]
            }
          }
        PAPERLESS_LOGOUT_REDIRECT_URL: https://authentik.${CLUSTER_DOMAIN}/application/o/paperless/end-session/
        PAPERLESS_AUTO_LOGIN: "true"
        PAPERLESS_AUTO_CREATE: "true"
  dataFrom:
    - extract:
        key: paperless
