---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .SECRET_KEY }}"
  dataFrom:
    - extract:
        key: paperless
